'use server';

/**
 * @fileOverview This file defines a Genkit flow for solving math exercises from a photo.
 *
 * The flow takes an image of an exercise as input and returns a detailed, step-by-step solution generated by AI.
 *
 * - solveExerciseFromPhoto - A function that handles the process of solving the exercise from a photo.
 * - SolveExerciseFromPhotoInput - The input type for the solveExerciseFromPhoto function.
 * - SolveExerciseFromPhotoOutput - The return type for the solveExerciseFromPhoto function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SolveExerciseFromPhotoInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'A photo of the exercise, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'
    ),
  subject: z.string().describe('The subject of the exercise (e.g., Math, Physics).'),
});
export type SolveExerciseFromPhotoInput = z.infer<typeof SolveExerciseFromPhotoInputSchema>;

const SolveExerciseFromPhotoOutputSchema = z.object({
  solution: z.string().describe('A detailed, step-by-step solution to the exercise.'),
});
export type SolveExerciseFromPhotoOutput = z.infer<typeof SolveExerciseFromPhotoOutputSchema>;

export async function solveExerciseFromPhoto(
  input: SolveExerciseFromPhotoInput
): Promise<SolveExerciseFromPhotoOutput> {
  return solveExerciseFromPhotoFlow(input);
}

const solveExerciseFromPhotoPrompt = ai.definePrompt({
  name: 'solveExerciseFromPhotoPrompt',
  input: {schema: SolveExerciseFromPhotoInputSchema},
  output: {schema: SolveExerciseFromPhotoOutputSchema},
  prompt: `You are an expert tutor specializing in providing detailed, step-by-step solutions to exercises for students in Côte d'Ivoire.

  Your response must follow these rules:
  1.  **Default Language is French:** Unless the subject is a foreign language, solve and explain everything in French.
  2.  **Language Exercises:**
      - If the subject is 'Anglais' (English), 'Allemand' (German), or 'Espagnol' (Spanish), you MUST provide the solution and the step-by-step explanation **in that specific language**.
      - **After** providing the solution in the target language, you MUST add a clear separator (e.g., '--- EXPLICATION EN FRANÇAIS ---') and then provide a summary explanation of the solution **in French**. This is for the user's comprehension.
  3.  **Clarity and Pedagogy:** Always provide a comprehensive solution that explains each step clearly, as if you were teaching a student.

  Subject: {{{subject}}}
  Exercise Image: {{media url=photoDataUri}}
  `,
});

const solveExerciseFromPhotoFlow = ai.defineFlow(
  {
    name: 'solveExerciseFromPhotoFlow',
    inputSchema: SolveExerciseFromPhotoInputSchema,
    outputSchema: SolveExerciseFromPhotoOutputSchema,
  },
  async input => {
    const {output} = await solveExerciseFromPhotoPrompt(input);
    return output!;
  }
);
