// This file is the entry point for your cloud functions.
// It's automatically generated by the build process.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const admin = require("firebase-admin");
const functions = require("firebase-functions");
const next = require("next");
admin.initializeApp();
const isDev = process.env.NODE_ENV !== "production";
const app = next({
    dev: isDev,
    conf: { distDir: "../.next" },
});
const handle = app.getRequestHandler();
// HTTPS function for Next.js
exports.nextjsFunc = functions.https.onRequest(async (req, res) => {
    await app.prepare();
    return handle(req, res);
});
// Export other functions
var on_user_create_1 = require("./on-user-create");
Object.defineProperty(exports, "onUserCreate", { enumerable: true, get: function () { return on_user_create_1.onUserCreate; } });
